#!/usr/bin/env zsh

PROJECT_DIR="$(git rev-parse --show-toplevel)"

cd "$PROJECT_DIR"

rm -rf dist
mkdir -p dist
cp -r test dist
parcel build index.html --public-url './'

rsync -av --delete dist/ steno:image-tagger/

OUTDIR="/data/projects/macrostrat/image-tagger"
ssh -t steno "sudo rsync -av image-tagger/ $OUTDIR/"
