#!/usr/bin/env zsh

PROJECT_DIR="$(git rev-parse --show-toplevel)"

cd "$PROJECT_DIR"
npm run-script build
rsync -av --delete dist/ steno:image-tagger/

OUTDIR="/data/projects/macrostrat/image-tagger"
ssh -t steno "sudo rsync -av image-tagger/ $OUTDIR/"

