#!/bin/sh

(cd ui-components & npm install)
npm install

echo "PUBLIC_URL: $PUBLIC_URL"
echo "API_BASE_URL: $API_BASE_URL"
echo "IMAGE_BASE_URL: $IMAGE_BASE_URL"

# Make sure we nuke previous dist files, for some
# reason this matters
rm -rf dist/*.*

# If not in development mode, we do not need to build the
# frontend files, so we simply exit.
if [ -z "$DEBUG" ]; then
  parcel build --public-url "$PUBLIC_URL" index.html
  exit 0
fi

parcel watch --hmr-port 34365 --public-url "$PUBLIC_URL" index.html
