FROM node:11-alpine
WORKDIR /user

RUN npm install --unsafe-perm -g linklocal concurrently
COPY ./bundled-deps/ui-components /user/bundled-deps/ui-components
COPY ./package.json /user
RUN npm install --unsafe-perm

ENV PUBLIC_URL="/"
ENV API_BASE_URL="${PUBLIC_URL}search"
ENV IMAGE_BASE_URL="${PUBLIC_URL}images/"
ENV APPMODE="ANNOTATION"

RUN npm install --unsafe-perm -g linklocal concurrently
COPY . /user
CMD ./run-docker ${MODE:-tagging}
