FROM node:11-alpine
WORKDIR /user

COPY . /user
RUN npm install -g linklocal && npm install

ENV PUBLIC_URL="/"
ENV API_BASE_URL="${PUBLIC_URL}search"
ENV IMAGE_BASE_URL="${PUBLIC_URL}images/"
ENV APPMODE="PREDICTION"

CMD ./run-docker visualizer

# FROM nginx
# COPY --from=0 /user/dist /frontend
# COPY ./nginx.frontend-only.conf /etc/nginx/nginx.conf
