#!/bin/sh
# provide the argument 'tagging', 'validation', or 'visualizer'

PATH="/user/node_modules/.bin:$PATH"

(cd ./bundled-deps/ui-components && npm install)
npm install

if [ ENVIRONMENT = "production" ]; then
  cd bundled-deps/ui-components && npm run build
  webpack --config webpack.$1.js
  exit 0
fi

webpack --config webpack.$1.js \
  --watch --mode=development & \
(cd bundled-deps/ui-components && npm run dev)
