#!/usr/bin/env bash
# Run locally for development
# provide the argument 'tagging', 'validation', or 'visualizer'

export PATH="node_modules/.bin:$PATH"

env="local-env.sh"
[ -f $env ] && source $env
[ -z $API_BASE_URL ] && echo "API_BASE_URL not provided. Please create a local-env.sh file" && exit 1

export PUBLIC_URL=${PUBLIC_URL:-/}
export MODE=${MODE:-development}

(cd bundled-deps/ui-components && npm run dev) & \
webpack-dev-server --entry $(pwd)/src/${1:-visualizer}-app/index.ts
