#!/bin/sh
cp api_key.js.example api_key.js
uuid=$(node -e "const uuidv4 = require('uuid/v4'); console.log(uuidv4());")
echo $uuid
sed -i "s|secret key|$uuid|g" api_key.js
sqlite3 annotations.sqlite < schema.sql
sqlite3 annotations.sqlite "INSERT INTO people (name) VALUES ('dummy');"

