#!/bin/sh



# Wait until PostgreSQL is available
# and then set up the schema
node setup.js "/images/test" test

if [ -z "${IMAGE_TAGGER_API_MODE}" ]
then
    echo "No startup mode specified -- assumed prediction ingest."
    MODE='prediction'
else
    MODE='annotate'
fi

if [ "$MODE" = "prediction" ]
then
  # Not sure if this is the proper API
  python import_predictions.py /xml /images
  nodemon npm start
elif [ "$MODE" = "annotate" ]
then
  #node setup.js images dummy_import &
  nodemon npm start
else
  echo "I don't know what to do."
  exit 1
fi


